
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monolithic-app
    ports:
      - "9000:80"      # Apache (Laravel)
      - "5173:5173"    # Vite (Vue + frontend)
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
    environment:
      - VITE_APP_URL=http://localhost:9000
      - APP_URL=http://localhost:9000
      - ASSET_URL=http://localhost:9000
    env_file:
      - .env
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
