name: Deploy to test server

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, ctype, fileinfo, json, pdo_mysql, tokenizer, xml
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install npm dependencies
        run: npm install

      - name: Build assets with Vite
        run: npm run build

      - name: Parse SSH Key
        run: echo "${{ secrets.SSH_TEST_PRIVATE_KEY }}" > private_key && chmod 600 private_key

      - name: Deploy to test Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_TEST_IP }}
          username: ${{ secrets.SSH_TEST_USER }}
          key: ${{ secrets.SSH_TEST_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.APP_TEST_DIR }}
            git fetch origin
            git reset --hard origin/develop
            composer install --no-interaction --prefer-dist --optimize-autoloader
            npm install
            npm run build
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan optimize
